Set-ExecutionPolocy -ExecutionPolicy Bypass -Scope Process -Force
Invoke-Expression ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
choco install -y 7zip
choco install -y ag
choco install -y altdrag
choco install -y alacritty
choco install -y arduino
choco install -y autohotkey
choco install -y chromium
choco install -y cmake
choco install -y colortool
choco install -y curl
choco install -y dia
choco install -y edgedeflector
choco install -y everything
choco install -y foobar2000
choco install -y fzf
choco install -y gimp
choco install -y git
choco install -y git-lfs
choco install -y git-status-cache-posh-client
choco install -y ilspy
choco install -y inkscape
choco install -y kdiff3
choco install -y licecap
choco install -y linqpad
choco install -y microsoft-teams
choco install -y neovim
choco install -y nextcloud-client
choco install -y nuget.commandline
choco install -y openssh
choco install -y sharpkeys
choco install -y sqlite
choco install -y StrawberryPerl
choco install -y sumatrapdf.install
choco install -y swig
choco install -y sysinternals
choco install -y visualstudiocode
choco install -y wget
choco install -y windirstat
choco install -y yarn
choco install -y zeal
