Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
Invoke-Expression ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
choco install -y 7zip
choco install -y ag
choco install -y altdrag
choco install -y arduino
choco install -y autohotkey
choco install -y chromium
choco install -y cmake
choco install -y colortool
choco install -y ctags
choco install -y curl
choco install -y dia
choco install -y dependencywalker
choco install -y docbook-bundle
choco install -y edgedeflector
choco install -y Everything
choco install -y ext2fsd
choco install -y ffmpeg
choco install -y filezilla
choco install -y Firefox
choco install -y flashplayerplugin
choco install -y foobar2000
choco install -y fzf
choco install -y gimp
choco install -y git
choco install -y git-credential-manager-for-windows
choco install -y git-status-cache-posh-client
choco install -y git-lfs
choco install -y ilspy
choco install -y inkscape
choco install -y irfanview
choco install -y kdiff3
choco install -y lame
choco install -y licecap
choco install -y linqpad
choco install -y microsoft-teams
choco install -y --pre neovim
choco install -y make
choco install -y nextcloud-client
choco install -y nodejs
choco install -y nuget.commandline
choco install -y nvs
choco install -y openscad
choco install -y openssh
choco install -y Paket
choco install -y Paket.PowerShell
choco install -y postman
choco install -y procmon
choco install -y python2
choco install -y ripgrep
choco install -y rsync
choco install -y ruby
choco install -y sharpkeys
choco install -y simulide
choco install -y SQLite
choco install -y StrawberryPerl
choco install -y sumatrapdf
choco install -y swig
choco install -y sysinternals
choco install -y tixati
choco install -y vcredist140
choco install -y vcredist2008
choco install -y vcredist2010
choco install -y vcredist2013
choco install -y vcredist2015
choco install -y vcredist2017
choco install -y visualstudiocode
choco install -y vlc
choco install -y vscode
choco install -y Wget
choco install -y windirstat
choco install -y wsltty
choco install -y yarn
choco install -y zeal
choco install -y zulu
