theme: 0
showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
mixinType: 1
mixinCode: |-
  module.exports.parse = ({ content, name, url }, { yaml, axios, notify }) => {
    var os = process.platform
    var dns_cfg = {
      dns: {
        enable: true,
        "enhanced-mode": "redir-host",
        nameserver: [
          "8.8.8.8",
          "114.114.114.114"
        ],
        fallback: [
          "https://doh.pub/dns-query"
        ],
        "fallback-filter": {
          geoip: false,
          ipcidr: ["0.0.0.0/32"]
        }
      }
    }
    var tun_cfg = {}
    if (os === "win32") {
      tun_cfg = {
        "ignore-resolve-fail": true,
        tun: {
          enable: true,
          stack: "gvisor",
          "dns-hijack": ["198.18.0.2:53"],
          "auto-route": true,
          "auto-detect-interface": true,
        }
      }
    } else { // linux
      tun_cfg = {
        tun: {
          enable: true,
          stack: "system",
          "dns-hijack": ["1.0.0.1:53"],
        }
      }
    }
    return { ...content, ...dns_cfg, ...tun_cfg }
  }
iconSpeed: false
showNotifications: true
